version: '3.8'

services:
  bbms-php-db:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    container_name: bbms-php-db
    restart: unless-stopped
    user: root
    environment:
      MYSQL_USER: bbms
      MYSQL_PASSWORD: bbms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bbms
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    
  bbms-php:
    container_name: bbms-php
    build:
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/bbms
      - ../apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - bbms-php-db